name: notion_api
description: A wrapper for the public beta Notion API to manage it like a Notion SDK package for dart.
version: 1.2.0
homepage: https://github.com/jonathangomz/notion_api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  test: ^1.17.5
  dotenv: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec